#### 1. Import pandas library

In [5]:
import pandas as pd

#### 2. Import pymysql and sqlalchemy as you have learnt in the lesson of importing/exporting data

In [6]:
import pymysql
from sqlalchemy import create_engine

#### 3. Create a mysql engine to set the connection to the server. Check the connection details in [this link](https://relational.fit.cvut.cz/search?tableCount%5B%5D=0-10&tableCount%5B%5D=10-30&dataType%5B%5D=Numeric&databaseSize%5B%5D=KB&databaseSize%5B%5D=MB)

In [12]:
engine = create_engine('mysql+pymysql://guest:relational@relational.fit.cvut.cz/stats')

#### 4. Import the users table

In [19]:
users = pd.read_sql_query('SELECT * FROM stats.users', engine)
users.head()

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId,Age,ProfileImageUrl
0,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,1920,-1,NaN,None
1,2,101,2010-07-19 14:01:36,Geoff Dalgas,2013-11-12 22:07:23,http://stackoverflow.com,"Corvallis, OR",<p>Developer on the StackOverflow team. Find ...,25,3,0,2,37.0,None
2,3,101,2010-07-19 15:34:50,Jarrod Dixon,2014-08-08 06:42:58,http://stackoverflow.com,"New York, NY","<p><a href=""http://blog.stackoverflow.com/2009...",22,19,0,3,35.0,None
3,4,101,2010-07-19 19:03:27,Emmett,2014-01-02 09:31:02,http://minesweeperonline.com,"San Francisco, CA",<p>currently at a startup in SF</p>\n\n<p>form...,11,0,0,1998,28.0,http://i.stack.imgur.com/d1oHX.jpg
4,5,6792,2010-07-19 19:03:57,Shane,2014-08-13 00:23:47,http://www.statalgo.com,"New York, NY",<p>Quantitative researcher focusing on statist...,1145,662,5,54503,35.0,None

#### 5. Rename Id column to userId

In [20]:
users = data.rename(columns={'Id': 'userId'})
users.head()

,userId,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId,Age,ProfileImageUrl
0,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,1920,-1,NaN,None
1,2,101,2010-07-19 14:01:36,Geoff Dalgas,2013-11-12 22:07:23,http://stackoverflow.com,"Corvallis, OR",<p>Developer on the StackOverflow team. Find ...,25,3,0,2,37.0,None
2,3,101,2010-07-19 15:34:50,Jarrod Dixon,2014-08-08 06:42:58,http://stackoverflow.com,"New York, NY","<p><a href=""http://blog.stackoverflow.com/2009...",22,19,0,3,35.0,None
3,4,101,2010-07-19 19:03:27,Emmett,2014-01-02 09:31:02,http://minesweeperonline.com,"San Francisco, CA",<p>currently at a startup in SF</p>\n\n<p>form...,11,0,0,1998,28.0,http://i.stack.imgur.com/d1oHX.jpg
4,5,6792,2010-07-19 19:03:57,Shane,2014-08-13 00:23:47,http://www.statalgo.com,"New York, NY",<p>Quantitative researcher focusing on statist...,1145,662,5,54503,35.0,None

#### 6. Import the posts table.

In [24]:
posts = pd.read_sql_query('SELECT * FROM stats.posts', engine)
posts.head()

,Id,PostTypeId,AcceptedAnswerId,CreaionDate,Score,ViewCount,Body,OwnerUserId,LasActivityDate,Title,...,AnswerCount,CommentCount,FavoriteCount,LastEditorUserId,LastEditDate,CommunityOwnedDate,ParentId,ClosedDate,OwnerDisplayName,LastEditorDisplayName
0,1,1,15.0,2010-07-19 19:12:12,23,1278.0,<p>How should I elicit prior distributions fro...,8.0,2010-09-15 21:08:26,Eliciting priors from experts,...,5.0,1,14.0,NaN,NaT,NaT,NaN,NaT,None,None
1,2,1,59.0,2010-07-19 19:12:57,22,8198.0,<p>In many different statistical methods there...,24.0,2012-11-12 09:21:54,What is normality?,...,7.0,1,8.0,88.0,2010-08-07 17:56:44,NaT,NaN,NaT,None,None
2,3,1,5.0,2010-07-19 19:13:28,54,3613.0,<p>What are some valuable Statistical Analysis...,18.0,2013-05-27 14:48:36,What are some valuable Statistical Analysis op...,...,19.0,4,36.0,183.0,2011-02-12 05:50:03,2010-07-19 19:13:28,NaN,NaT,None,None
3,4,1,135.0,2010-07-19 19:13:31,13,5224.0,<p>I have two groups of data. Each with a dif...,23.0,2010-09-08 03:00:19,Assessing the significance of differences in d...,...,5.0,2,2.0,NaN,NaT,NaT,NaN,NaT,None,None
4,5,2,NaN,2010-07-19 19:14:43,81,NaN,"<p>The R-project</p>\n\n<p><a href=""http://www...",23.0,2010-07-19 19:21:15,None,...,NaN,3,NaN,23.0,2010-07-19 19:21:15,2010-07-19 19:14:43,3.0,NaT,None,None

#### 7. Rename Id column to postId and OwnerUserId to userId

In [25]:
posts = posts.rename(columns={'Id': 'postId', 'OwnerUserId': 'userId'})
posts.head()

,postId,PostTypeId,AcceptedAnswerId,CreaionDate,Score,ViewCount,Body,userId,LasActivityDate,Title,...,AnswerCount,CommentCount,FavoriteCount,LastEditorUserId,LastEditDate,CommunityOwnedDate,ParentId,ClosedDate,OwnerDisplayName,LastEditorDisplayName
0,1,1,15.0,2010-07-19 19:12:12,23,1278.0,<p>How should I elicit prior distributions fro...,8.0,2010-09-15 21:08:26,Eliciting priors from experts,...,5.0,1,14.0,NaN,NaT,NaT,NaN,NaT,None,None
1,2,1,59.0,2010-07-19 19:12:57,22,8198.0,<p>In many different statistical methods there...,24.0,2012-11-12 09:21:54,What is normality?,...,7.0,1,8.0,88.0,2010-08-07 17:56:44,NaT,NaN,NaT,None,None
2,3,1,5.0,2010-07-19 19:13:28,54,3613.0,<p>What are some valuable Statistical Analysis...,18.0,2013-05-27 14:48:36,What are some valuable Statistical Analysis op...,...,19.0,4,36.0,183.0,2011-02-12 05:50:03,2010-07-19 19:13:28,NaN,NaT,None,None
3,4,1,135.0,2010-07-19 19:13:31,13,5224.0,<p>I have two groups of data. Each with a dif...,23.0,2010-09-08 03:00:19,Assessing the significance of differences in d...,...,5.0,2,2.0,NaN,NaT,NaT,NaN,NaT,None,None
4,5,2,NaN,2010-07-19 19:14:43,81,NaN,"<p>The R-project</p>\n\n<p><a href=""http://www...",23.0,2010-07-19 19:21:15,None,...,NaN,3,NaN,23.0,2010-07-19 19:21:15,2010-07-19 19:14:43,3.0,NaT,None,None

#### 8. Define new dataframes for users and posts with the following selected columns:
    **users columns**: userId, Reputation,Views,UpVotes,DownVotes
    **posts columns**: postId, Score,userID,ViewCount,CommentCount

In [33]:
users_columns = users.filter(['userId', 'Reputation', 'Views', 'UpVotes', 'DownVotes'])
posts_columns = posts.filter(['postId', 'Score', 'userID', 'ViewCount', 'CommentCount'])

#### 8. Merge both dataframes, users and posts. 
You will need to make a [merge](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html) of posts and users dataframes.

In [37]:
users_posts = users.merge(posts)

#### 9. How many missing values do you have in your merged dataframe? On which columns?

In [40]:
null_cols = users_posts.isnull().sum()
null_cols[null_cols > 0]

WebsiteUrl               58513
Location                 50132
AboutMe                  48900
Age                      63780
ProfileImageUrl          66521
AcceptedAnswerId         76021
ViewCount                48396
Body                       220
Title                    48396
Tags                     48396
AnswerCount              48396
FavoriteCount            77605
LastEditorUserId         46456
LastEditDate             46228
CommunityOwnedDate       88197
ParentId                 43484
ClosedDate               89024
OwnerDisplayName         89463
LastEditorDisplayName    90335
dtype: int64

#### 10. You will need to make something with missing values.  Will you clean or filling them? Explain. 
**Remember** to check the results of your code before passing to the next step

In [47]:
#I will remove most of the columns as the missing values in each are in several dosens of thousands
#I will only keep Body and futhre explore the missing values

drop_cols = list(null_cols[null_cols > 10000].index)
users_posts = users_posts.drop(drop_cols, axis=1)

null_displ = users_posts[(users_posts['Body'].isnull()==True)]
null_displ
#Cannot really idetify a correlation for empty 'Body' fields to other fields, will leave as is

,userId,Reputation,CreationDate,DisplayName,LastAccessDate,Views,UpVotes,DownVotes,AccountId,postId,PostTypeId,CreaionDate,Score,Body,LasActivityDate,CommentCount
1,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,8576,5,2011-03-21 17:40:28,0,None,2011-03-21 17:40:28,0
2,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,8578,5,2011-03-21 17:46:43,0,None,2011-03-21 17:46:43,0
5,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,9857,3,2011-04-22 06:59:10,0,None,2011-04-22 06:59:10,0
7,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,9860,5,2011-04-22 07:09:42,0,None,2011-04-22 07:09:42,0
8,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,10130,3,2011-04-29 00:18:02,0,None,2011-04-29 00:18:02,0
9,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,10131,3,2011-04-29 00:18:02,0,None,2011-04-29 00:18:02,0
13,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,16366,5,2011-10-02 18:27:56,0,None,2011-10-02 18:27:56,0
14,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,19423,5,2011-12-06 09:43:26,0,None,2011-12-06 09:43:26,0
15,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,19848,5,2011-12-15 02:38:20,0,None,2011-12-15 02:38:20,0
21,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,20485,5,2012-01-02 18:07:38,0,None,2012-01-02 18:07:38,0
22,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,20487,5,2012-01-02 18:08:36,0,None,2012-01-02 18:08:36,0
25,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21497,5,2012-01-22 15:04:34,0,None,2012-01-22 15:04:34,0
26,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21795,5,2012-01-27 01:25:07,0,None,2012-01-27 01:25:07,0
27,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21856,5,2012-01-28 09:37:15,0,None,2012-01-28 09:37:15,0
28,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21860,5,2012-01-28 09:46:15,0,None,2012-01-28 09:46:15,0
29,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21861,4,2012-01-28 09:46:15,0,None,2012-01-28 09:46:15,0
30,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21862,5,2012-01-28 09:48:49,0,None,2012-01-28 09:48:49,0
31,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21864,5,2012-01-28 09:50:31,0,None,2012-01-28 09:50:31,0
32,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21876,5,2012-01-28 19:47:12,0,None,2012-01-28 19:47:12,0
33,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21878,5,2012-01-28 19:50:00,0,None,2012-01-28 19:50:00,0
34,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,21882,5,2012-01-28 19:57:45,0,None,2012-01-28 19:57:45,0
35,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,23847,5,2012-02-29 06:41:22,0,None,2012-02-29 06:41:22,0
36,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,27148,5,2012-04-26 01:08:49,0,None,2012-04-26 01:08:49,0
37,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,28215,5,2012-05-10 22:14:30,0,None,2012-05-10 22:14:30,0
38,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,28223,5,2012-05-10 23:10:31,0,None,2012-05-10 23:10:31,0
39,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,28240,5,2012-05-11 03:14:43,0,None,2012-05-11 03:14:43,0
40,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,28260,5,2012-05-11 13:00:09,0,None,2012-05-11 13:00:09,0
41,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,28263,5,2012-05-11 13:00:47,0,None,2012-05-11 13:00:47,0
42,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,28267,5,2012-05-11 13:17:46,0,None,2012-05-11 13:17:46,0
43,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,0,5007,1920,-1,28269,5,2012-05-11 13:21:06,0,None,2012-05-11 13:21:06,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7605,686,44152,2010-08-03 19:42:40,Peter Flom,2014-09-13 22:08:44,7357,2156,82,80800,63343,5,2013-07-04 14:03:55,0,None,2013-07-04 14:03:55,0
7609,686,44152,2010-08-03 19:42:40,Peter Flom,2014-09-13 22:08:44,7357,2156,82,80800,63373,5,2013-07-04 23:53:51,0,None,2013-07-04 23:53:51,0
7615,686,44152,2010-08-03 19:42:40,Peter Flom,2014-09-13 22:08:44,7357,2156,82,80800,63449,5,2013-07-05 13:57:24,0,None,2013-07-05 13:57:24,0
7810,686,44152,2010-08-03 19:42:40,Peter Flom,2014-09-13 22:08:44,7357,2156,82,80800,73889,5,2013-10-27 21:12:43,0,None,2013-10-27 21:12:43,0
7812,686,44152,2010-08-03 19:42:40,Peter Flom,2014-09-13 22:08:44,7357,2156,82,80800,73933,5,2013-10-28 10:42:29,0,None,2013-10-28 10:42:29,0
7832,686,44152,2010-08-03 19:42:40,Peter Flom,2014-09-13 22:08:44,7357,2156,82,80800,74454,5,2013-11-03 11:27:30,0,None,2013-11-03 11:27:30,0
9574,805,65272,2010-08-07 08:40:07,Glen_b,2014-09-14 03:01:20,5680,7035,143,131001,78824,5,2013-12-07 01:22:34,0,None,2013-12-07 01:22:34,0
11563,919,87393,2010-08-13 15:29:47,whuber,2014-09-14 00:51:49,20932,11273,779,449752,9209,5,2011-04-05 16:46:53,0,None,2011-04-05 16:46:53,0
11772,919,87393,2010-08-13 15:29:47,whuber,2014-09-14 00:51:49,20932,11273,779,449752,18364,5,2011-11-14 18:41:27,0,None,2011-11-14 18:41:27,0
11808,919,87393,2010-08-13 15:29:47,whuber,2014-09-14 00:51:49,20932,11273,779,449752,20696,5,2012-01-07 01:57:19,0,None,2012-01-07 01:57:19,0
12047,919,87393,2010-08-13 15:29:47,whuber,2014-09-14 00:51:49,20932,11273,779,449752,44277,5,2012-11-23 15:07:06,0,None,2012-11-23 15:07:06,0
12289,919,87393,2010-08-13 15:29:47,whuber,2014-09-14 00:51:49,20932,11273,779,449752,82618,5,2014-01-17 17:11:36,0,None,2014-01-17 17:11:36,0
12840,930,31170,2010-08-13 20:50:47,chl,2014-09-13 20:53:41,5529,10523,214,184175,18646,5,2011-11-19 21:28:00,0,None,2011-11-19 21:28:00,0
12862,930,31170,2010-08-13 20:50:47,chl,2014-09-13 20:53:41,5529,10523,214,184175,21877,4,2012-01-28 19:47:12,0,None,2012-01-28 19:47:12,0
12894,930,31170,2010-08-13 20:50:47,chl,2014-09-13 20:53:41,5529,10523,214,184175,34123,5,2012-08-11 09:28:51,0,None,2012-08-11 09:28:51,0
12907,930,31170,2010-08-13 20:50:47,chl,2014-09-13 20:53:41,5529,10523,214,184175,64366,5,2013-07-15 13:31:02,0,None,2013-07-15 13:31:02,0
34513,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,66318,5,2013-08-02 03:12:15,0,None,2013-08-02 03:12:15,0
34515,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,66320,5,2013-08-02 03:21:28,0,None,2013-08-02 03:21:28,0
34523,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,66840,5,2013-08-08 13:29:59,0,None,2013-08-08 13:29:59,0
34528,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,67079,5,2013-08-11 17:01:04,0,None,2013-08-11 17:01:04,0
34533,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,67216,5,2013-08-13 01:28:06,0,None,2013-08-13 01:28:06,0
34536,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,67587,5,2013-08-16 15:52:18,0,None,2013-08-16 15:52:18,0
34538,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,67589,5,2013-08-16 15:53:29,0,None,2013-08-16 15:53:29,0
34558,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,70194,5,2013-09-16 22:45:32,0,None,2013-09-16 22:45:32,0
34566,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,71182,5,2013-09-26 19:54:04,0,None,2013-09-26 19:54:04,0
34577,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,72983,5,2013-10-16 18:34:20,0,None,2013-10-16 18:34:20,0
34592,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,76603,5,2013-11-14 20:47:42,0,None,2013-11-14 20:47:42,0
34594,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,76631,5,2013-11-15 02:17:54,0,None,2013-11-15 02:17:54,0
34674,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,90803,5,2014-03-21 03:21:59,0,None,2014-03-21 03:21:59,0
34703,7290,37083,2011-11-09 04:43:15,gung,2014-09-14 02:10:14,5554,8641,125,1028075,93185,5,2014-04-09 14:54:47,0,None,2014-04-09 14:54:47,0

#### 11. Adjust the data types in order to avoid future issues. Which ones should be changed?

In [49]:
users_posts .dtypes

userId                      int64
Reputation                  int64
CreationDate       datetime64[ns]
DisplayName                object
LastAccessDate     datetime64[ns]
Views                       int64
UpVotes                     int64
DownVotes                   int64
AccountId                   int64
postId                      int64
PostTypeId                  int64
CreaionDate        datetime64[ns]
Score                       int64
Body                       object
LasActivityDate    datetime64[ns]
CommentCount                int64
dtype: object

In [ ]:
#data['year'] = data['year'].astype('object') 
#data['year'].dtype

#### Bonus: Identify extreme values in your merged dataframe as you have learned in class, create a dataframe called outliers with the same columns as our data set and calculate the bounds. The values of the outliers dataframe will be the values of the merged_df that fall outside that bounds. You will need to save your outliers dataframe to a csv file on your-code folder.

In [54]:
stats = users_posts.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats

outliers = pd.DataFrame(columns=users_posts.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = users_posts[(users_posts[col] < lower) | 
                   (users_posts[col] > upper)].copy()
    results['Outlier'] = col 
    outliers = outliers.append(results)
outliers

,AccountId,Body,CommentCount,CreaionDate,CreationDate,DisplayName,DownVotes,LasActivityDate,LastAccessDate,Outlier,PostTypeId,Reputation,Score,UpVotes,Views,postId,userId
1155,154667,"<p>In such a discussion, I always recall the f...",0,2010-07-19 19:51:34,2010-07-19 19:35:37,mbq,126,2010-07-19 19:51:34,2014-09-13 10:26:43,Reputation,2,14082,25,4235,3320,74,88
1156,154667,"<p>Quick R site is basic, but quite nice for s...",0,2010-07-19 20:18:24,2010-07-19 19:35:37,mbq,126,2010-07-19 20:18:24,2014-09-13 10:26:43,Reputation,2,14082,5,4235,3320,94,88
1157,154667,"<p><a href=""http://cran.r-project.org/web/pack...",1,2010-07-19 20:25:08,2010-07-19 19:35:37,mbq,126,2010-07-19 20:25:08,2014-09-13 10:26:43,Reputation,2,14082,7,4235,3320,99,88
1158,154667,<p>There are many reasons; probably the main i...,3,2010-07-19 21:11:44,2010-07-19 19:35:37,mbq,126,2013-04-27 14:09:42,2014-09-13 10:26:43,Reputation,2,14082,6,4235,3320,119,88
1159,154667,<p>The official guides are pretty nice; check ...,0,2010-07-19 21:39:35,2010-07-19 19:35:37,mbq,126,2010-07-19 21:39:35,2014-09-13 10:26:43,Reputation,2,14082,7,4235,3320,140,88
1160,154667,<p>Neural network may be to slow for a large n...,2,2010-07-19 21:48:28,2010-07-19 19:35:37,mbq,126,2010-07-19 21:48:28,2014-09-13 10:26:43,Reputation,2,14082,5,4235,3320,143,88
1161,154667,"<p>It may be an overshoot, but you may train a...",1,2010-07-20 09:30:51,2010-07-19 19:35:37,mbq,126,2010-07-20 09:30:51,2014-09-13 10:26:43,Reputation,2,14082,8,4235,3320,255,88
1162,154667,<p>In plain English: If your classifier miscla...,0,2010-07-20 10:05:48,2010-07-19 19:35:37,mbq,126,2010-07-20 10:17:16,2014-09-13 10:26:43,Reputation,2,14082,14,4235,3320,265,88
1163,154667,"<p>In case of Poisson it is bad, since counts ...",0,2010-07-20 11:29:53,2010-07-19 19:35:37,mbq,126,2010-07-20 12:26:55,2014-09-13 10:26:43,Reputation,2,14082,5,4235,3320,275,88
1164,154667,<p>The fact that something more complex reduce...,1,2010-07-20 14:40:32,2010-07-19 19:35:37,mbq,126,2010-07-20 14:40:32,2014-09-13 10:26:43,Reputation,2,14082,2,4235,3320,309,88
1165,154667,<p>The entropy is only one (as a concept) -- t...,4,2010-07-20 17:20:41,2010-07-19 19:35:37,mbq,126,2010-07-20 17:36:23,2014-09-13 10:26:43,Reputation,2,14082,1,4235,3320,337,88
1166,154667,<p>Do you think that unbalanced classes is a b...,0,2010-07-20 18:12:29,2010-07-19 19:35:37,mbq,126,2012-04-24 22:17:17,2014-09-13 10:26:43,Reputation,1,14082,2,4235,3320,341,88
1167,154667,"<p><a href=""http://en.wikipedia.org/wiki/K-nea...",0,2010-07-20 18:16:17,2010-07-19 19:35:37,mbq,126,2010-07-20 18:16:17,2014-09-13 10:26:43,Reputation,2,14082,3,4235,3320,343,88
1168,154667,"<p><a href=""http://en.wikipedia.org/wiki/Naive...",2,2010-07-20 18:17:25,2010-07-19 19:35:37,mbq,126,2010-07-20 18:17:25,2014-09-13 10:26:43,Reputation,2,14082,3,4235,3320,344,88
1169,154667,<p>We try to minimize the variance that is lef...,4,2010-07-20 23:21:05,2010-07-19 19:35:37,mbq,126,2010-07-21 09:31:29,2014-09-13 10:26:43,Reputation,2,14082,6,4235,3320,358,88
1170,154667,<p>Does it really need some advanced model? Ba...,2,2010-07-20 23:56:33,2010-07-19 19:35:37,mbq,126,2010-07-20 23:56:33,2014-09-13 10:26:43,Reputation,2,14082,4,4235,3320,360,88
1171,154667,"<p>You cannot prove, because it is impossible;...",0,2010-07-21 06:15:36,2010-07-19 19:35:37,mbq,126,2010-07-21 06:15:36,2014-09-13 10:26:43,Reputation,2,14082,3,4235,3320,380,88
1172,154667,"<p>Was XKCD, so time for Dilbert:</p>\n\n<p><i...",3,2010-07-21 15:21:33,2010-07-19 19:35:37,mbq,126,2010-07-21 15:21:33,2014-09-13 10:26:43,Reputation,2,14082,109,4235,3320,424,88
1173,154667,"<p>One more <a href=""http://dilbert.com/fast/2...",1,2010-07-21 15:53:59,2010-07-19 19:35:37,mbq,126,2010-07-21 15:53:59,2014-09-13 10:26:43,Reputation,2,14082,84,4235,3320,435,88
1174,154667,"<p>For us, it is just one example of a robust ...",3,2010-07-21 17:30:02,2010-07-19 19:35:37,mbq,126,2010-07-21 17:30:02,2014-09-13 10:26:43,Reputation,2,14082,6,4235,3320,450,88
1175,154667,<p>In the physics field there is a rule that t...,0,2010-07-21 20:11:02,2010-07-19 19:35:37,mbq,126,2010-07-21 20:11:02,2014-09-13 10:26:43,Reputation,2,14082,8,4235,3320,462,88
1176,154667,"<p>If this is about your ""Qnotifier"" I think t...",4,2010-07-21 20:34:43,2010-07-19 19:35:37,mbq,126,2010-07-21 20:34:43,2014-09-13 10:26:43,Reputation,2,14082,3,4235,3320,464,88
1177,154667,"<p>The main idea is the bagging procedure, not...",2,2010-07-22 09:53:52,2010-07-19 19:35:37,mbq,126,2013-02-14 05:32:34,2014-09-13 10:26:43,Reputation,2,14082,14,4235,3320,483,88
1178,154667,"<p>Generally, it is assumed that AIC (and so A...",2,2010-07-22 11:42:42,2010-07-19 19:35:37,mbq,126,2010-07-22 20:16:08,2014-09-13 10:26:43,Reputation,2,14082,6,4235,3320,494,88
1179,154667,<p>Backward elimination.</p>\n\n<p>Start with ...,7,2010-07-22 12:17:20,2010-07-19 19:35:37,mbq,126,2010-07-22 13:05:25,2014-09-13 10:26:43,Reputation,2,14082,3,4235,3320,501,88
1180,154667,<p>Metropolis scanning / MCMC</p>\n\n<ul>\n<li...,0,2010-07-22 12:42:13,2010-07-19 19:35:37,mbq,126,2010-07-22 12:42:13,2014-09-13 10:26:43,Reputation,2,14082,5,4235,3320,505,88
1181,154667,"<p>Try <a href=""http://www.r-project.org/"" rel...",1,2010-07-22 16:24:10,2010-07-19 19:35:37,mbq,126,2010-07-22 16:24:10,2014-09-13 10:26:43,Reputation,2,14082,3,4235,3320,518,88
1182,154667,"<p>As you know, there are two popular types of...",0,2010-07-22 19:17:41,2010-07-19 19:35:37,mbq,126,2010-07-24 22:54:13,2014-09-13 10:26:43,Reputation,1,14082,7,4235,3320,526,88
1183,154667,<p>There is also a problem with the opposite c...,0,2010-07-23 08:33:04,2010-07-19 19:35:37,mbq,126,2010-07-23 08:33:04,2014-09-13 10:26:43,Reputation,2,14082,8,4235,3320,547,88
1184,154667,<p>The general idea is that you should scale t...,0,2010-07-23 16:30:41,2010-07-19 19:35:37,mbq,126,2010-07-23 16:30:41,2014-09-13 10:26:43,Reputation,2,14082,5,4235,3320,559,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89728,4901181,<p>I have 11 variables in my data set.<br>\nfa...,9,2014-08-17 05:53:54,2014-08-17 05:23:43,Kasun Harshana Bandara,0,2014-08-20 08:18:20,2014-09-08 18:25:14,CommentCount,1,1,0,0,0,112169,54210
89740,4338185,"<p>I have four variables, two are categorical ...",12,2014-08-17 18:13:08,2014-08-17 17:52:02,Si never sighs,0,2014-08-18 09:45:42,2014-09-10 17:35:01,CommentCount,1,16,0,1,0,112263,54229
89774,3676667,<p>I've got two sets of data from some fluores...,12,2014-08-18 17:51:56,2014-08-18 17:34:01,Okoning,0,2014-08-19 10:53:48,2014-09-06 13:53:55,CommentCount,1,118,2,0,2,112351,54279
89789,4908465,<p>I cannot post comments yet so I am going to...,9,2014-08-19 18:28:02,2014-08-18 23:58:55,Dan,6,2014-08-19 18:28:02,2014-09-04 21:49:57,CommentCount,2,60,-2,14,64,112504,54300
89794,4908465,<p>I am not familiar with PyMC but this should...,8,2014-08-21 18:34:24,2014-08-18 23:58:55,Dan,6,2014-08-21 19:07:12,2014-09-04 21:49:57,CommentCount,2,60,1,14,64,112816,54300
89800,4908465,<p>Since you say that you have a large amount ...,14,2014-08-27 22:34:58,2014-08-18 23:58:55,Dan,6,2014-08-27 22:56:53,2014-09-04 21:49:57,CommentCount,2,60,3,14,64,113498,54300
89911,4912133,<p>I am working on the project that requires d...,11,2014-08-19 17:44:22,2014-08-21 15:35:50,Pooja,0,2014-08-21 16:22:49,2014-08-26 18:48:02,CommentCount,1,6,1,0,0,112567,54474
89965,452200,<p>I'm a beginner in BUGS. I'm trying to code ...,14,2014-08-23 21:00:37,2014-08-23 21:00:21,v4r,0,2014-08-25 18:49:48,2014-08-29 21:17:08,CommentCount,1,111,2,0,2,113011,54581
89985,4935070,"<p><img src=""http://i.stack.imgur.com/yc6o9.pn...",10,2014-09-03 17:32:54,2014-08-24 20:10:24,private private,0,2014-09-04 02:28:46,2014-09-03 18:14:49,CommentCount,1,1,0,0,0,114212,54619
90051,2931088,<p>It looks like that one should assume that t...,8,2014-08-28 00:45:02,2014-08-26 13:12:37,higgsss,0,2014-08-30 00:57:21,2014-09-14 02:37:02,CommentCount,2,576,2,49,37,113508,54724
90062,4943422,<p>I'm trying to analyze the effect of the lay...,11,2014-08-26 14:53:10,2014-08-26 14:53:10,Cheyenne,0,2014-08-26 14:53:10,2014-08-28 11:45:37,CommentCount,1,1,0,0,2,113299,54733
90064,4943898,<p>I'm Stata-proficient but learning SPSS for ...,17,2014-08-26 16:33:17,2014-08-26 16:28:20,ShannonC,0,2014-08-26 21:43:08,2014-09-12 21:46:18,CommentCount,1,96,7,5,14,113314,54736
90067,4943898,<p>When using multiple dummies for a categoric...,8,2014-09-04 16:23:42,2014-08-26 16:28:20,ShannonC,0,2014-09-04 16:29:45,2014-09-12 21:46:18,CommentCount,1,96,2,5,14,114356,54736
90071,4944618,<p>I am confused on what I have read about the...,9,2014-08-26 19:16:22,2014-08-26 19:16:22,adam,0,2014-08-29 23:06:08,2014-09-04 21:22:29,CommentCount,1,16,3,0,1,113334,54741
90098,3849649,<p>I would like to know if there is a differen...,8,2014-08-27 14:31:09,2014-08-27 15:16:57,Mohr,0,2014-08-28 09:14:24,2014-09-01 21:50:24,CommentCount,1,20,0,1,2,113540,54791
90120,34330,<p>I'm working on statistics for software buil...,8,2014-08-28 06:31:03,2014-08-28 06:05:22,Kim Gräsman,0,2014-09-04 01:09:05,2014-09-08 19:02:23,CommentCount,1,163,12,4,6,113526,54840
90130,4954127,<p>This question is about three-way interactio...,17,2014-08-28 16:58:03,2014-08-28 14:59:56,Funn Me,0,2014-09-01 12:51:05,2014-09-07 15:30:02,CommentCount,1,14,2,3,9,113598,54862
90153,1481222,"<p>Let's say you have $X$ coins, each with a d...",8,2014-08-28 23:18:48,2014-08-28 23:16:47,Jacob Kranz,0,2014-08-29 17:05:16,2014-09-01 00:59:51,CommentCount,1,108,1,2,0,113650,54896
90162,4696433,<p>I extract data related to a movie by sentim...,11,2014-08-29 12:41:53,2014-08-29 09:49:15,user3801185,0,2014-08-29 12:41:53,2014-09-09 13:37:09,CommentCount,1,1,0,0,1,113691,54911
90185,4961981,<p>I took two statistics classes at college an...,9,2014-08-30 12:43:56,2014-08-30 12:43:56,Faisal,0,2014-08-30 19:19:21,2014-08-30 15:22:48,CommentCount,1,16,3,0,0,113790,54953
90227,4967343,<p>I have monthly data at physician level (sal...,11,2014-09-01 06:34:43,2014-09-01 09:02:47,Apurba Gorai,0,2014-09-01 08:48:53,2014-09-08 11:44:59,CommentCount,1,1,0,0,1,113934,55020
90244,4970491,<p>Is there some restriction to parameters $( ...,12,2014-09-01 21:20:46,2014-09-01 21:20:46,micheal,0,2014-09-02 15:19:43,2014-09-02 15:29:26,CommentCount,1,14,2,0,1,114004,55053
90251,4972628,<p>I am studying the distribution of a marine ...,8,2014-09-02 10:21:04,2014-09-02 09:59:22,seke20,0,2014-09-03 10:28:30,2014-09-08 14:00:31,CommentCount,1,1,0,0,0,114045,55086
90259,197017,<p>I am working on a project where I need to c...,10,2014-09-02 15:34:15,2014-09-02 15:21:18,mkoistinen,0,2014-09-04 21:04:23,2014-09-12 18:14:13,CommentCount,1,111,2,0,4,114081,55107
90268,3935246,<p>I'm analyzing a data set that has an extrem...,11,2014-09-02 21:18:20,2014-09-02 21:18:20,Troy Griffiths,0,2014-09-02 23:51:52,2014-09-09 19:59:09,CommentCount,1,6,1,0,0,114119,55125
90274,4975713,<p>I'm trying to find the name of this method ...,10,2014-09-02 23:48:45,2014-09-02 23:36:37,missng,0,2014-09-03 23:33:44,2014-09-12 15:16:58,CommentCount,1,13,2,0,0,114129,55135
90326,4984229,<p>I have some university rankings data where ...,8,2014-09-04 14:26:45,2014-09-04 14:25:11,Akash Kaura,0,2014-09-04 14:38:20,2014-09-04 15:11:46,CommentCount,1,6,1,0,3,114339,55241
90346,2863153,<p>Hi I am fit a maxwell distribution and atte...,8,2014-09-09 17:20:43,2014-09-05 16:49:03,Abhinav Kumar,0,2014-09-09 22:39:54,2014-09-12 12:06:56,CommentCount,1,13,2,0,0,114859,55302
90408,5000552,<p>We have fitted a nonlinear function to obse...,9,2014-09-08 15:53:27,2014-09-08 15:07:39,Marco,0,2014-09-09 14:40:20,2014-09-11 10:58:50,CommentCount,1,11,2,0,1,114719,55420
90491,4543924,<p>I have a set of 'activity' values for some ...,9,2014-09-10 17:42:37,2014-09-10 19:25:03,Joe Healey,0,2014-09-13 03:19:04,2014-09-13 11:54:42,CommentCount,1,6,1,0,3,115020,55557

In [55]:
outliers.to_csv('~/Desktop/Ironhack/Cours/data-labs/module-1/lab-data_cleaning/your-code/outliers.csv', sep=',', index=False)