In [1]:
import pandas as pd
import numpy as np

In [2]:
#Import file:
shark = pd.read_csv('~/Desktop/Ironhack/Cours/data-labs/module-1/pandas-project/GSAF5.csv', encoding='latin1')

#Set to show all column/row names
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#Check head rows only:
shark.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [3]:
#Print all column names:
shark.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [4]:
#Strip spaces from column names:
shark.columns = shark.columns.str.strip()

#Could also use rename function:
#shark = shark.rename(columns={'Sex ':'Sex', 'Species ':'Species'})

In [5]:
#Row count:
print('Number of total rows: ', shark.shape[0])

#Missing Values:
null_cols = shark.isnull().sum()
null_cols[null_cols > 0]

Number of total rows:  5992

Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
href formula                 1
href                         3
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

In [6]:
#Drop 2 last columns as they are empty:
shark = shark.drop(['Unnamed: 22', 'Unnamed: 23'], axis=1)
shark.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989

In [7]:
#Examine columns with similar missing value count and try finidng correlation
null_displ = shark[(shark['Fatal (Y/N)'].isnull()==True) & (shark['Injury'].isnull()!=True)]
null_displ = null_displ[['Type', 'Activity', 'Injury', 'Fatal (Y/N)', 'Investigator or Source']]
null_displ

,Type,Activity,Injury,Fatal (Y/N),Investigator or Source
54,Unprovoked,Spearfishing,"No injury, but sharks repeatedly hit their fin...",NaN,"Gold Coast Bulletin, 6/4/2016"
1844,Invalid,Kayaking,Reported as shark attack but probable drowning,NaN,"R. D. Weeks, GSAF"
2449,Invalid,Scuba diving,FATAL,NaN,"LA Times, 7/28/1989"
3280,Provoked,Scuba diving,"Diver shot the shark, then it injured his arm ...",NaN,C. Moore. GSAF
3435,Invalid,Spearfishing,"Disappeared, probable drowning but sharks in a...",NaN,C. Moore. GSAF
3901,Boat,Fishing,Boat damaged,NaN,"C. Moore, GSAF"
4107,Boating,Fishing trawler Flavio Gioia,No injury to occupants. Shark tore nets & traw...,NaN,"C. Moore, GSAF"
4112,Invalid,NaN,Human remains found in shark,NaN,"C. Moore, GSAF"
5307,Invalid,Swimming,"Disappeared, but shark involvement unconfirmed",NaN,C. Moore
5437,Invalid,Fishing boat,"No injury, no attack",NaN,"C.Moore, GSAF"
5468,Invalid,NaN,"Human remains found in 4m, 900 kg shark",NaN,"C. Moore, GSAF"
5642,Invalid,Fishing,No injury,NaN,"C. Moore, GSAF"
5699,Invalid,NaN,Possible drowning and scavenging,NaN,C. Moore
5718,Unprovoked,Fell overboard,FATAL,NaN,"Pacific Commercial Advertiser, 3/24/1850"
5747,Invalid,NaN,Death preceded shark involvement,NaN,Norway Heritage
5793,Invalid,NaN,Shark caught contained human remains,NaN,W. H. Gregg
5794,Invalid,NaN,"Shark caught, contained human remains",NaN,"C. Moore, GSAF"
5820,Invalid,NaN,Probable drowning,NaN,"C. Moore, GSAF"
5849,Invalid,NaN,"Partial hominid remains recovered from shark, ...",NaN,E. Olafsen

In [8]:
# Read the injury comments and try to fill in manually if fatal or no (based on row nb):

shark['Fatal (Y/N)'][54] = 'N'
shark['Fatal (Y/N)'][2449] = 'Y'
shark['Fatal (Y/N)'][3901] = 'N'
shark['Fatal (Y/N)'][4107] = 'N'
shark['Fatal (Y/N)'][5437] = 'N'
shark['Fatal (Y/N)'][5718] = 'Y'
shark['Fatal (Y/N)'][5747] = 'Y'

#Not sure what's the error below; values have been replaced

/Users/laumaustupa/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/laumaustupa/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/laumaustupa/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/laumaustupa/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/laumaustupa/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/laumaustupa/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/laumaustupa/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [ ]:
print(shark['Fatal (Y/N)'][54], 
shark['Fatal (Y/N)'][2449], 
shark['Fatal (Y/N)'][3901], 
shark['Fatal (Y/N)'][4107],
shark['Fatal (Y/N)'][5437],
shark['Fatal (Y/N)'][5718],
shark['Fatal (Y/N)'][5747])

N Y N N N Y Y

In [ ]:
#Replace "No details" with NaN
shark['Injury'] = shark['Injury'].replace('No details', np.nan)

In [ ]:
#Low Variance Columns; identifying columns where 90% of the data is the same:

low_variance = []

for col in shark._get_numeric_data():
    minimum = min(shark[col])
    ninety_perc = np.percentile(shark[col], 90)
    if ninety_perc == minimum:
        low_variance.append(col)

print(low_variance)

[]

In [ ]:
#Cleaning Text and Removing Special Characters
#Check unique values of a column:

print(set(shark['Sex']))

{nan, '.', 'N', 'lli', 'M ', 'M', 'F'}

In [ ]:
#Replace other charachters, or abrievations to make data more homogeneous:
shark['Sex'] = shark['Sex'].replace('N', np.nan)
shark['Sex'] = shark['Sex'].replace('lli', np.nan)
shark['Sex'] = shark['Sex'].replace('.', np.nan)
shark['Sex'] = shark['Sex'].str.replace('M ', 'M')

print(set(shark['Sex']))

{nan, 'M', 'F'}

In [ ]:
#Checking data in other columns:
print(set(shark['Fatal (Y/N)']))

{nan, ' N', 'F', 'N', 'UNKNOWN', 'N ', '#VALUE!', 'n', 'Y'}

In [ ]:
shark['Fatal (Y/N)'] = shark['Fatal (Y/N)'].str.replace(' N', 'N')
shark['Fatal (Y/N)'] = shark['Fatal (Y/N)'].str.replace('N ', 'N')
shark['Fatal (Y/N)'] = shark['Fatal (Y/N)'].str.replace('n', 'N')
shark['Fatal (Y/N)'] = shark['Fatal (Y/N)'].str.replace('F', 'Y')
shark['Fatal (Y/N)'] = shark['Fatal (Y/N)'].replace('#VALUE!', np.nan)
shark['Fatal (Y/N)'] = shark['Fatal (Y/N)'].replace('UNKNOWN', np.nan)
print(set(shark['Fatal (Y/N)']))

{nan, 'N', 'Y'}

In [ ]:
print(set(shark['Country']))

{nan, 'NORTH ATLANTIC OCEAN', 'UNITED ARAB EMIRATES', 'EGYPT / ISRAEL', ' PHILIPPINES', 'TONGA', 'RUSSIA', 'ITALY', 'SOLOMON ISLANDS / VANUATU', 'NICARAGUA ', 'PACIFIC OCEAN', 'ST. MAARTIN', 'HONDURAS', 'COSTA RICA', 'GREENLAND', 'WESTERN SAMOA', 'SENEGAL', 'SIERRA LEONE', 'INDONESIA', 'GREECE', 'BRITISH NEW GUINEA', 'ARUBA', 'NEW CALEDONIA', 'COLUMBIA', 'NORTH PACIFIC OCEAN', 'KUWAIT', 'VANUATU', 'LIBYA', 'YEMEN ', 'PERSIAN GULF', 'NORTHERN ARABIAN SEA', 'ANTIGUA', 'THAILAND', 'BRITISH VIRGIN ISLANDS', 'BAY OF BENGAL', 'SLOVENIA', 'INDIAN OCEAN', 'HAITI', 'SOUTHWEST PACIFIC OCEAN', 'GUATEMALA', 'MEXICO', 'DIEGO GARCIA', 'ALGERIA', 'AUSTRALIA', 'KIRIBATI', 'TANZANIA', 'NEVIS', 'FRENCH POLYNESIA', 'SUDAN', 'CENTRAL PACIFIC', 'EQUATORIAL GUINEA / CAMEROON', 'MADAGASCAR', 'LIBERIA', 'ST. MARTIN', 'BELIZE', 'Between PORTUGAL & INDIA', 'INDIAN OCEAN?', 'ECUADOR', 'TURKS & CAICOS', 'IRAN', 'SAMOA', 'OCEAN', 'KENYA', 'FALKLAND ISLANDS', 'ANGOLA', 'GUAM', 'MALAYSIA', 'SRI LANKA', 'CYPRUS', 'IRELAND', 'GRENADA', 'GUYANA', 'BRAZIL', 'MALDIVE ISLANDS', 'IRAN / IRAQ', 'HONG KONG', 'SPAIN', 'DOMINICAN REPUBLIC', 'ENGLAND', 'SOLOMON ISLANDS', 'MAURITIUS', 'SAN DOMINGO', 'SINGAPORE', 'Seychelles', 'ANDAMAN / NICOBAR ISLANDAS', 'DJIBOUTI', 'BAHAMAS', 'PHILIPPINES', 'PORTUGAL', 'Fiji', 'MEXICO ', 'THE BALKANS', 'CAYMAN ISLANDS', 'MEDITERRANEAN SEA', 'ATLANTIC OCEAN', 'BAHREIN', 'UNITED KINGDOM', 'PALESTINIAN TERRITORIES', 'ARGENTINA', 'Coast of AFRICA', 'MALTA', 'JOHNSTON ISLAND', 'SEYCHELLES', 'TUNISIA', 'CROATIA', 'RED SEA', 'SOUTH CHINA SEA', 'GHANA', 'FIJI', 'SYRIA', 'SOUTH AFRICA', 'YEMEN', 'EL SALVADOR', 'COOK ISLANDS', 'St Helena', 'Sierra Leone', ' TONGA', 'VIETNAM', 'GUINEA', 'NORWAY', 'CUBA', 'BRITISH ISLES', 'OKINAWA', 'AMERICAN SAMOA', 'RED SEA?', 'NICARAGUA', 'ITALY / CROATIA', 'URUGUAY', 'CEYLON (SRI LANKA)', 'MOZAMBIQUE', 'FRANCE', 'NORTHERN MARIANA ISLANDS', 'MICRONESIA', 'GULF OF ADEN', 'BRITISH WEST INDIES', 'TURKEY', 'SOUTH KOREA', 'MARSHALL ISLANDS', 'SCOTLAND', 'INDIA', 'LEBANON', 'EGYPT ', 'PARAGUAY', 'JAVA', 'SOUTH ATLANTIC OCEAN', 'TASMAN SEA', 'ISRAEL', 'CARIBBEAN SEA', 'MARTINIQUE', 'MEDITERRANEAN SEA?', 'NAMIBIA', 'CRETE', 'REUNION', 'BURMA', 'GRAND CAYMAN', 'NORTH ATLANTIC OCEAN ', 'CHINA', 'SAUDI ARABIA', 'GABON', 'CURACAO', 'FEDERATED STATES OF MICRONESIA', 'NEW GUINEA', 'TRINIDAD & TOBAGO', 'MAYOTTE', 'TAIWAN', 'SOMALIA', 'BERMUDA', 'TUVALU', 'ADMIRALTY ISLANDS', 'PANAMA', 'VENEZUELA', 'PACIFIC OCEAN ', 'SUDAN?', 'BARBADOS', 'NEW ZEALAND', 'PAPUA NEW GUINEA', 'KOREA', 'PUERTO RICO', 'MID-PACIFC OCEAN', 'GEORGIA', 'MID ATLANTIC OCEAN', 'SOUTH PACIFIC OCEAN', 'MONACO', 'JAPAN', 'JAMAICA', 'UNITED ARAB EMIRATES (UAE)', 'ASIA?', 'CHILE', 'RED SEA / INDIAN OCEAN', 'CAPE VERDE', 'IRAQ', 'NIGERIA', 'AZORES', 'EGYPT', 'SWEDEN', 'PALAU', 'NEW BRITAIN', 'USA', 'NETHERLANDS ANTILLES', 'BANGLADESH', 'MONTENEGRO', 'CANADA', 'ICELAND', 'NORTH SEA'}

In [ ]:
# !! Can try to fill in missing country names based on list above (if possible)

null_country = shark[(shark['Country'].isnull()==True)&(shark['Area'].isnull()!=True)]
null_country = null_country[['Country', 'Area', 'Location']]
null_country

In [ ]:
print(set(shark['Age']))

In [ ]:
#Cleaning up data in Age column:

shark['Age'] = shark['Age'].replace('MAKE LINE GREEN', np.nan)
shark['Age'] = shark['Age'].replace(' ', np.nan)
shark['Age'] = shark['Age'].replace('  ', np.nan)
shark['Age'] = shark['Age'].replace('X', np.nan)
shark['Age'] = shark['Age'].replace('F', np.nan)
shark['Age'] = shark['Age'].replace('M', np.nan)
shark['Age'] = shark['Age'].replace('A.M.', np.nan)
shark['Age'] = shark['Age'].replace('\xa0 ', np.nan)

shark['Age'] = shark['Age'].str.replace('Ca. ', '')
shark['Age'] = shark['Age'].str.replace('?', '')
shark['Age'] = shark['Age'].str.replace('T', 't')
shark['Age'] = shark['Age'].str.replace('   ', '')
shark['Age'] = shark['Age'].str.replace('   ', '')
shark['Age'] = shark['Age'].str.replace('"', '')
shark['Age'] = shark['Age'].str.replace('(', '')
shark['Age'] = shark['Age'].str.replace(')', '')

In [ ]:
print(set(shark['Age']))

In [ ]:
print(set(shark['Year']))

In [ ]:
shark.loc[(shark['Year']== 0)]
# Correlation for Case number & year: 
# if case number starts with ND = No date, Year = 0
# if case number starts with 0: BC

In [ ]:
# For B.C. cases change the value in year to -1 to be able to do binning
shark.loc[(shark['Year']==0) & (shark['Case Number'].str.startswith('0.')), "Year"]= -1
shark.loc[(shark['Year']== -1)]

In [ ]:
#Binning Year to group accidents by year
year_labels = ['B.C', 'No Date', '0-1900', '1901-1950', '1951-2000', 'After 2001']
cutoffs = [-1000, -1, 0, 1900, 1950, 2000, 3000]
bins = pd.cut(shark['Year'], cutoffs, labels=year_labels)
bins.value_counts(sort=False)

In [ ]:
#Declare dataframe without the cases that have date as "Reported" 
#meaning that they are dates of the report, not of the accident itself
wo_reported = shark.loc[(shark['Case Number'].str.endswith('R'))!= True]

In [ ]:
#Binning Year to group accidents by year, without the ones with reported date
year_labels = ['B.C', 'No Date', '0-1900', '1901-1950', '1951-2000', 'After 2001']
cutoffs = [-1000, -1, 0, 1900, 1950, 2000, 3000]
bins = pd.cut(wo_reported['Year'], cutoffs, labels=year_labels)
bins.value_counts(sort=False)

In [ ]:
#Data Type Correction
shark.dtypes

In [ ]:
#Set Year to int type:
shark['Year'] = shark['Year'].astype('int64') 
shark['Year'].dtype

In [ ]:
#Extreme Values and Outliers:
stats = shark.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats

In [ ]:
outliers = pd.DataFrame(columns=shark.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = shark[(shark[col] < lower) | 
                   (shark[col] > upper)].copy()
    results['Outlier'] = col #this added column will show the initial data set column name that contains the outlier
    outliers = outliers.append(results)
    
outliers.head()

In [ ]:
#Save as csv:
outliers.to_csv('~/Desktop/Ironhack/Cours/data-labs/module-1/pandas-project/your-code/outliers.csv', sep=',', index=False)

In [ ]:
#Finding and Removing Duplicates:
before = len(shark)
shark = shark.drop_duplicates()
after = len(shark)
print('Number of duplicate records dropped: ', str(before - after))

In [ ]:
# !! See if possible drop duplicates based on certain columns only:
# select_columns = ['need', 'to', 'list', 'columns'] 
# shark = shark[select_columns].drop_duplicates() 
# after = len(shark) 
# print('Number of duplicate records dropped: ', str(before - after))

In [ ]:
#Exporting a clean CSV version of data:
shark.to_csv('~/Desktop/Ironhack/Cours/data-labs/module-1/pandas-project/your-code/shark-clean.csv', sep=',', index=False)