# Challenge 3

In this challenge we will work on the `Orders.csv` data set in the previous [Subsetting and Descriptive Stats lab](../../lab-subsetting-and-descriptive-stats/your-code/main.ipynb). In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

# Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [2]:
# import required libraries
import numpy as np
import pandas as pd

Next, import `Orders.csv` from the "subsetting" lab folder into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [37]:
# enter your code here
orders = pd.read_csv("../../lab-subsetting-and-descriptive-stats/your-code/Orders.csv")
orders

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
5,5,536365,22752,2010,12,3,8,set 7 babushka nesting boxes,2,2010-12-01 08:26:00,7.65,17850,United Kingdom,15.30
6,6,536365,21730,2010,12,3,8,glass star frosted t-light holder,6,2010-12-01 08:26:00,4.25,17850,United Kingdom,25.50
7,7,536366,22633,2010,12,3,8,hand warmer union jack,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10
8,8,536366,22632,2010,12,3,8,hand warmer red polka dot,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10
9,9,536367,84879,2010,12,3,8,assorted colour bird ornament,32,2010-12-01 08:34:00,1.69,13047,United Kingdom,54.08
10,10,536367,22745,2010,12,3,8,poppy's playhouse bedroom,6,2010-12-01 08:34:00,2.10,13047,United Kingdom,12.60
11,11,536367,22748,2010,12,3,8,poppy's playhouse kitchen,6,2010-12-01 08:34:00,2.10,13047,United Kingdom,12.60
12,12,536367,22749,2010,12,3,8,feltcraft princess charlotte doll,8,2010-12-01 08:34:00,3.75,13047,United Kingdom,30.00
13,13,536367,22310,2010,12,3,8,ivory knitted mug cosy,6,2010-12-01 08:34:00,1.65,13047,United Kingdom,9.90
14,14,536367,84969,2010,12,3,8,box of 6 assorted colour teaspoons,6,2010-12-01 08:34:00,4.25,13047,United Kingdom,25.50
15,15,536367,22623,2010,12,3,8,box of vintage jigsaw blocks,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85
16,16,536367,22622,2010,12,3,8,box of vintage alphabet blocks,2,2010-12-01 08:34:00,9.95,13047,United Kingdom,19.90
17,17,536367,21754,2010,12,3,8,home building block word,3,2010-12-01 08:34:00,5.95,13047,United Kingdom,17.85
18,18,536367,21755,2010,12,3,8,love building block word,3,2010-12-01 08:34:00,5.95,13047,United Kingdom,17.85
19,19,536367,21777,2010,12,3,8,recipe box with metal heart,4,2010-12-01 08:34:00,7.95,13047,United Kingdom,31.80
20,20,536367,48187,2010,12,3,8,doormat new england,4,2010-12-01 08:34:00,7.95,13047,United Kingdom,31.80
21,21,536368,22960,2010,12,3,8,jam making set with jars,6,2010-12-01 08:34:00,4.25,13047,United Kingdom,25.50
22,22,536368,22913,2010,12,3,8,red coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85
23,23,536368,22912,2010,12,3,8,yellow coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85
24,24,536368,22914,2010,12,3,8,blue coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85
25,25,536369,21756,2010,12,3,8,bath building block word,3,2010-12-01 08:35:00,5.95,13047,United Kingdom,17.85
26,26,536370,22728,2010,12,3,8,alarm clock bakelike pink,24,2010-12-01 08:45:00,3.75,12583,France,90.00
27,27,536370,22727,2010,12,3,8,alarm clock bakelike red,24,2010-12-01 08:45:00,3.75,12583,France,90.00
28,28,536370,22726,2010,12,3,8,alarm clock bakelike green,12,2010-12-01 08:45:00,3.75,12583,France,45.00
29,29,536370,21724,2010,12,3,8,panda and bunnies sticker sheet,12,2010-12-01 08:45:00,0.85,12583,France,10.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397894,541879,581585,22726,2011,12,5,12,alarm clock bakelike green,8,2011-12-09 12:31:00,3.75,15804,United Kingdom,30.00
397895,541880,581585,22727,2011,12,5,12,alarm clock bakelike red,4,2011-12-09 12:31:00,3.75,15804,United Kingdom,15.00
397896,541881,581585,16016,2011,12,5,12,large chinese style scissor,10,2011-12-09 12:31:00,0.85,15804,United Kingdom,8.50
397897,541882,581585,21916,2011,12,5,12,set 12 retro white chalk sticks,24,2011-12-09 12:31:00,0.42,15804,United Kingdom,10.08
397898,541883,581585,84692,2011,12,5,12,box of 24 cocktail parasols,25,2011-12-09 12:31:00,0.42,15804,United Kingdom,10.50
397899,541884,581585,84946,2011,12,5,12,antique silver t-light glass,12,2011-12-09 12:31:00,1.25,15804,United Kingdom,15.00
397900,541885,581585,21684,2011,12,5,12,small medina stamped metal bowl,12,2011-12-09 12:31:00,0.85,15804,United Kingdom,10.20
397901,541886,581585,22398,2011,12,5,12,magnets pack of 4 swallows,12,2011-12-09 12:31:00,0.39,15804,United Kingdom,4.68
397902,541887,581585,23328,2011,12,5,12,set 6 school milk bottles in crate,4,2011-12-09 12:31:00,3.75,15804,United Kingdom,15.00
397903,541888,581585,23145,2011,12,5,12,zinc t-light holder star large,12,2011-12-09 12:31:00,0.95,15804,United Kingdom,11.40
397904,541889,581585,22466,2011,12,5,12,fairy tale cottage night light,12,2011-12-09 12:31:00,1.95,15804,United Kingdom,23.40
397905,541890,581586,22061,2011,12,5,12,large cake stand hanging strawbery,8,2011-12-09 12:49:00,2.95,13113,United Kingdom,23.60
397906,541891,581586,23275,2011,12,5,12,set of 3 hanging owls ollie beak,24,2011-12-09 12:49:00,1.25,13113,United Kingdom,30.00
397907,541892,581586,21217,2011,12,5,12,red retrospot round cake tins,24,2011-12-09 12:49:00,8.95,13113,United Kingdom,214.80
397908,541893,581586,20685,2011,12,5,12,doormat red retrospot,10,2011-12-09 12:49:00,7.08,13113,United Kingdom,70.80
397909,541894,581587,22631,2011,12,5,12,circus parade lunch box,12,2011-12-09 12:50:00,1.95,12680,France,23.40
397910,541895,581587,22556,2011,12,5,12,plasters in tin circus parade,12,2011-12-09 12:50:00,1.65,12680,France,19.80
397911,541896,581587,22555,2011,12,5,12,plasters in tin strongman,12,2011-12-09 12:50:00,1.65,12680,France,19.80
397912,541897,581587,22728,2011,12,5,12,alarm clock bakelike pink,4,2011-12-09 12:50:00,3.75,12680,France,15.00
397913,541898,581587,22727,2011,12,5,12,alarm clock bakelike red,4,2011-12-09 12:50:00,3.75,12680,France,15.00
397914,541899,581587,22726,2011,12,5,12,alarm clock bakelike green,4,2011-12-09 12:50:00,3.75,12680,France,15.00
397915,541900,581587,22730,2011,12,5,12,alarm clock bakelike ivory,4,2011-12-09 12:50:00,3.75,12680,France,15.00
397916,541901,581587,22367,2011,12,5,12,childrens apron spaceboy design,8,2011-12-09 12:50:00,1.95,12680,France,15.60
397917,541902,581587,22629,2011,12,5,12,spaceboy lunch box,12,2011-12-09 12:50:00,1.95,12680,France,23.40
397918,541903,581587,23256,2011,12,5,12,childrens cutlery spaceboy,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397919,541904,581587,22613,2011,12,5,12,pack of 20 spaceboy napkins,12,2011-12-09 12:50:00,0.85,12680,France,10.20
397920,541905,581587,22899,2011,12,5,12,children's apron dolly girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60
397921,541906,581587,23254,2011,12,5,12,childrens cutlery dolly girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397922,541907,581587,23255,2011,12,5,12,childrens cutlery circus parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397923,541908,581587,22138,2011,12,5,12,baking set 9 piece retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [4]:
# your code here
# How to aggregate the  amount_spent for unique customers?

cust_spend = orders.groupby(['CustomerID'])[['amount_spent']].sum()
cust_spend.sort_values('amount_spent')

            amount_spent
CustomerID
13256               0.00
16738               3.75
14792               6.20
16454               6.90
17956              12.75
16878              13.30
15823              15.00
17763              15.00
13307              15.00
16093              17.00
16953              20.80
17986              20.80
17102              25.50
18268              25.50
15657              30.00
13120              30.60
17408              32.65
16765              34.00
15744              34.80
14576              35.40
16856              35.40
17831              35.40
15940              35.80
17816              36.56
16162              37.40
12855              38.10
18019              38.45
16659              39.12
12977              39.24
14589              39.75
...                  ...
17404           31906.82
15838           33643.08
12748           33719.73
16422           34684.40
16013           37130.60
13798           37153.85
15098           39916.50
17841           40991.57
12931           42055.96
15749           44534.30
14088           50491.81
14298           51527.30
15061           54534.14
15769           56252.72
17949           58510.48
13089           58825.83
15311           60767.90
13694           65039.62
14096           65164.79
16684           66653.56
12346           77183.60
16029           81024.84
17511           91062.38
14156          117379.63
12415          124914.53
14911          143825.06
16446          168472.50
17450          194550.79
18102          259657.30
14646          280206.02

[4339 rows x 1 columns]

In [10]:
# How to select customers whose aggregated amount_spent is in a given quantile range?
print(cust_spend.quantile(0.95))
cust_spend[cust_spend.amount_spent > cust_spend.amount_spent.quantile(0.95)].sort_values('amount_spent')

amount_spent    5840.182
Name: 0.95, dtype: float64

            amount_spent
CustomerID
13534            5870.08
13209            5891.61
14944            5900.25
14415            5900.28
14505            5905.64
15382            5955.71
14101            5976.79
13316            5977.73
13097            6010.42
12637            6021.90
14735            6065.69
15939            6115.01
17509            6115.14
13418            6127.43
14060            6140.42
12357            6207.67
14057            6217.96
16126            6287.77
17315            6292.26
15005            6316.57
13709            6328.05
13668            6363.59
12359            6372.58
13871            6403.25
13102            6424.09
13225            6463.84
15694            6479.40
18223            6484.54
12431            6487.45
16814            6509.10
...                  ...
17404           31906.82
15838           33643.08
12748           33719.73
16422           34684.40
16013           37130.60
13798           37153.85
15098           39916.50
17841           40991.57
12931           42055.96
15749           44534.30
14088           50491.81
14298           51527.30
15061           54534.14
15769           56252.72
17949           58510.48
13089           58825.83
15311           60767.90
13694           65039.62
14096           65164.79
16684           66653.56
12346           77183.60
16029           81024.84
17511           91062.38
14156          117379.63
12415          124914.53
14911          143825.06
16446          168472.50
17450          194550.79
18102          259657.30
14646          280206.02

[217 rows x 1 columns]

In [11]:
print(cust_spend.quantile(0.75))
cust_spend[(cust_spend.amount_spent > cust_spend.amount_spent.quantile(0.75)) 
           & (cust_spend.amount_spent < cust_spend.amount_spent.quantile(0.95))].sort_values('amount_spent')

amount_spent    1661.64
Name: 0.75, dtype: float64

            amount_spent
CustomerID
13012            1661.84
12530            1662.28
12912            1662.30
16115            1667.97
17656            1674.69
13149            1676.06
13647            1678.12
16638            1680.72
13577            1687.60
13162            1688.29
12635            1689.18
17152            1689.50
15380            1690.26
16671            1692.27
16813            1692.98
15549            1693.26
14245            1693.45
12764            1693.88
16775            1695.66
13824            1698.94
17193            1699.30
13184            1701.29
16007            1701.94
12843            1702.26
17282            1703.41
16398            1705.80
15240            1706.57
16902            1706.88
12407            1708.12
15947            1708.24
...                  ...
17719            5396.04
16701            5398.30
17809            5411.91
12490            5417.93
18198            5425.56
16265            5447.00
16985            5464.12
16609            5493.46
18225            5509.12
15805            5528.48
12539            5568.35
16161            5575.56
16767            5580.60
12839            5591.42
12481            5596.32
17757            5605.29
14688            5630.87
18118            5653.82
13004            5655.91
17716            5655.99
17049            5659.98
14049            5681.72
14110            5683.15
13468            5704.97
16553            5719.82
13178            5725.47
17686            5739.46
15218            5756.89
12720            5781.73
13050            5836.86

[868 rows x 1 columns]

In [20]:
# How to label selected customers as "VIP" or "Preferred"?¶
cust_spend['Label'] = np.where(
                            (cust_spend.amount_spent > cust_spend.amount_spent.quantile(0.75))
                            & (cust_spend.amount_spent < cust_spend.amount_spent.quantile(0.95)), 'Preferred',
                            np.where(cust_spend.amount_spent > cust_spend.amount_spent.quantile(0.95), 'VIP',
                            'Non Pref'))

cust_spend.sort_values('amount_spent')

            amount_spent     Label
CustomerID
13256               0.00  Non Pref
16738               3.75  Non Pref
14792               6.20  Non Pref
16454               6.90  Non Pref
17956              12.75  Non Pref
16878              13.30  Non Pref
15823              15.00  Non Pref
17763              15.00  Non Pref
13307              15.00  Non Pref
16093              17.00  Non Pref
16953              20.80  Non Pref
17986              20.80  Non Pref
17102              25.50  Non Pref
18268              25.50  Non Pref
15657              30.00  Non Pref
13120              30.60  Non Pref
17408              32.65  Non Pref
16765              34.00  Non Pref
15744              34.80  Non Pref
14576              35.40  Non Pref
16856              35.40  Non Pref
17831              35.40  Non Pref
15940              35.80  Non Pref
17816              36.56  Non Pref
16162              37.40  Non Pref
12855              38.10  Non Pref
18019              38.45  Non Pref
16659              39.12  Non Pref
12977              39.24  Non Pref
14589              39.75  Non Pref
...                  ...       ...
17404           31906.82       VIP
15838           33643.08       VIP
12748           33719.73       VIP
16422           34684.40       VIP
16013           37130.60       VIP
13798           37153.85       VIP
15098           39916.50       VIP
17841           40991.57       VIP
12931           42055.96       VIP
15749           44534.30       VIP
14088           50491.81       VIP
14298           51527.30       VIP
15061           54534.14       VIP
15769           56252.72       VIP
17949           58510.48       VIP
13089           58825.83       VIP
15311           60767.90       VIP
13694           65039.62       VIP
14096           65164.79       VIP
16684           66653.56       VIP
12346           77183.60       VIP
16029           81024.84       VIP
17511           91062.38       VIP
14156          117379.63       VIP
12415          124914.53       VIP
14911          143825.06       VIP
16446          168472.50       VIP
17450          194550.79       VIP
18102          259657.30       VIP
14646          280206.02       VIP

[4339 rows x 2 columns]

In [40]:
labels = cust_spend.filter(['CustomerID', 'Label'], axis=1)
labels
orders = pd.merge(orders, labels, on='CustomerID', how='left')
orders

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,Label
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,Preferred
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,Preferred
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,Preferred
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,Preferred
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,Preferred
5,5,536365,22752,2010,12,3,8,set 7 babushka nesting boxes,2,2010-12-01 08:26:00,7.65,17850,United Kingdom,15.30,Preferred
6,6,536365,21730,2010,12,3,8,glass star frosted t-light holder,6,2010-12-01 08:26:00,4.25,17850,United Kingdom,25.50,Preferred
7,7,536366,22633,2010,12,3,8,hand warmer union jack,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10,Preferred
8,8,536366,22632,2010,12,3,8,hand warmer red polka dot,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10,Preferred
9,9,536367,84879,2010,12,3,8,assorted colour bird ornament,32,2010-12-01 08:34:00,1.69,13047,United Kingdom,54.08,Preferred
10,10,536367,22745,2010,12,3,8,poppy's playhouse bedroom,6,2010-12-01 08:34:00,2.10,13047,United Kingdom,12.60,Preferred
11,11,536367,22748,2010,12,3,8,poppy's playhouse kitchen,6,2010-12-01 08:34:00,2.10,13047,United Kingdom,12.60,Preferred
12,12,536367,22749,2010,12,3,8,feltcraft princess charlotte doll,8,2010-12-01 08:34:00,3.75,13047,United Kingdom,30.00,Preferred
13,13,536367,22310,2010,12,3,8,ivory knitted mug cosy,6,2010-12-01 08:34:00,1.65,13047,United Kingdom,9.90,Preferred
14,14,536367,84969,2010,12,3,8,box of 6 assorted colour teaspoons,6,2010-12-01 08:34:00,4.25,13047,United Kingdom,25.50,Preferred
15,15,536367,22623,2010,12,3,8,box of vintage jigsaw blocks,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85,Preferred
16,16,536367,22622,2010,12,3,8,box of vintage alphabet blocks,2,2010-12-01 08:34:00,9.95,13047,United Kingdom,19.90,Preferred
17,17,536367,21754,2010,12,3,8,home building block word,3,2010-12-01 08:34:00,5.95,13047,United Kingdom,17.85,Preferred
18,18,536367,21755,2010,12,3,8,love building block word,3,2010-12-01 08:34:00,5.95,13047,United Kingdom,17.85,Preferred
19,19,536367,21777,2010,12,3,8,recipe box with metal heart,4,2010-12-01 08:34:00,7.95,13047,United Kingdom,31.80,Preferred
20,20,536367,48187,2010,12,3,8,doormat new england,4,2010-12-01 08:34:00,7.95,13047,United Kingdom,31.80,Preferred
21,21,536368,22960,2010,12,3,8,jam making set with jars,6,2010-12-01 08:34:00,4.25,13047,United Kingdom,25.50,Preferred
22,22,536368,22913,2010,12,3,8,red coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85,Preferred
23,23,536368,22912,2010,12,3,8,yellow coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85,Preferred
24,24,536368,22914,2010,12,3,8,blue coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85,Preferred
25,25,536369,21756,2010,12,3,8,bath building block word,3,2010-12-01 08:35:00,5.95,13047,United Kingdom,17.85,Preferred
26,26,536370,22728,2010,12,3,8,alarm clock bakelike pink,24,2010-12-01 08:45:00,3.75,12583,France,90.00,VIP
27,27,536370,22727,2010,12,3,8,alarm clock bakelike red,24,2010-12-01 08:45:00,3.75,12583,France,90.00,VIP
28,28,536370,22726,2010,12,3,8,alarm clock bakelike green,12,2010-12-01 08:45:00,3.75,12583,France,45.00,VIP
29,29,536370,21724,2010,12,3,8,panda and bunnies sticker sheet,12,2010-12-01 08:45:00,0.85,12583,France,10.20,VIP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397894,541879,581585,22726,2011,12,5,12,alarm clock bakelike green,8,2011-12-09 12:31:00,3.75,15804,United Kingdom,30.00,Preferred
397895,541880,581585,22727,2011,12,5,12,alarm clock bakelike red,4,2011-12-09 12:31:00,3.75,15804,United Kingdom,15.00,Preferred
397896,541881,581585,16016,2011,12,5,12,large chinese style scissor,10,2011-12-09 12:31:00,0.85,15804,United Kingdom,8.50,Preferred
397897,541882,581585,21916,2011,12,5,12,set 12 retro white chalk sticks,24,2011-12-09 12:31:00,0.42,15804,United Kingdom,10.08,Preferred
397898,541883,581585,84692,2011,12,5,12,box of 24 cocktail parasols,25,2011-12-09 12:31:00,0.42,15804,United Kingdom,10.50,Preferred
397899,541884,581585,84946,2011,12,5,12,antique silver t-light glass,12,2011-12-09 12:31:00,1.25,15804,United Kingdom,15.00,Preferred
397900,541885,581585,21684,2011,12,5,12,small medina stamped metal bowl,12,2011-12-09 12:31:00,0.85,15804,United Kingdom,10.20,Preferred
397901,541886,581585,22398,2011,12,5,12,magnets pack of 4 swallows,12,2011-12-09 12:31:00,0.39,15804,United Kingdom,4.68,Preferred
397902,541887,581585,23328,2011,12,5,12,set 6 school milk bottles in crate,4,2011-12-09 12:31:00,3.75,15804,United Kingdom,15.00,Preferred
397903,541888,581585,23145,2011,12,5,12,zinc t-light holder star large,12,2011-12-09 12:31:00,0.95,15804,United Kingdom,11.40,Preferred
397904,541889,581585,22466,2011,12,5,12,fairy tale cottage night light,12,2011-12-09 12:31:00,1.95,15804,United Kingdom,23.40,Preferred
397905,541890,581586,22061,2011,12,5,12,large cake stand hanging strawbery,8,2011-12-09 12:49:00,2.95,13113,United Kingdom,23.60,VIP
397906,541891,581586,23275,2011,12,5,12,set of 3 hanging owls ollie beak,24,2011-12-09 12:49:00,1.25,13113,United Kingdom,30.00,VIP
397907,541892,581586,21217,2011,12,5,12,red retrospot round cake tins,24,2011-12-09 12:49:00,8.95,13113,United Kingdom,214.80,VIP
397908,541893,581586,20685,2011,12,5,12,doormat red retrospot,10,2011-12-09 12:49:00,7.08,13113,United Kingdom,70.80,VIP
397909,541894,581587,22631,2011,12,5,12,circus parade lunch box,12,2011-12-09 12:50:00,1.95,12680,France,23.40,Non Pref
397910,541895,581587,22556,2011,12,5,12,plasters in tin circus parade,12,2011-12-09 12:50:00,1.65,12680,France,19.80,Non Pref
397911,541896,581587,22555,2011,12,5,12,plasters in tin strongman,12,2011-12-09 12:50:00,1.65,12680,France,19.80,Non Pref
397912,541897,581587,22728,2011,12,5,12,alarm clock bakelike pink,4,2011-12-09 12:50:00,3.75,12680,France,15.00,Non Pref
397913,541898,581587,22727,2011,12,5,12,alarm clock bakelike red,4,2011-12-09 12:50:00,3.75,12680,France,15.00,Non Pref
397914,541899,581587,22726,2011,12,5,12,alarm clock bakelike green,4,2011-12-09 12:50:00,3.75,12680,France,15.00,Non Pref
397915,541900,581587,22730,2011,12,5,12,alarm clock bakelike ivory,4,2011-12-09 12:50:00,3.75,12680,France,15.00,Non Pref
397916,541901,581587,22367,2011,12,5,12,childrens apron spaceboy design,8,2011-12-09 12:50:00,1.95,12680,France,15.60,Non Pref
397917,541902,581587,22629,2011,12,5,12,spaceboy lunch box,12,2011-12-09 12:50:00,1.95,12680,France,23.40,Non Pref
397918,541903,581587,23256,2011,12,5,12,childrens cutlery spaceboy,4,2011-12-09 12:50:00,4.15,12680,France,16.60,Non Pref
397919,541904,581587,22613,2011,12,5,12,pack of 20 spaceboy napkins,12,2011-12-09 12:50:00,0.85,12680,France,10.20,Non Pref
397920,541905,581587,22899,2011,12,5,12,children's apron dolly girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60,Non Pref
397921,541906,581587,23254,2011,12,5,12,childrens cutlery dolly girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60,Non Pref
397922,541907,581587,23255,2011,12,5,12,childrens cutlery circus parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60,Non Pref
397923,541908,581587,22138,2011,12,5,12,baking set 9 piece retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85,Non Pref

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

# Q2: How to identify which country has the most VIP Customers?

# Q3: How to identify which country has the most VIP+Preferred Customers combined?

Provide your solution for Q2 below:

In [51]:
# your code here
# Which country has the most VIP Customers?
orders[orders['Label'] == 'VIP']['Country'].value_counts()

United Kingdom     84185
EIRE                7077
France              3290
Germany             3127
Netherlands         2080
Australia            898
Portugal             681
Switzerland          594
Spain                511
Norway               420
Channel Islands      364
Finland              294
Cyprus               248
Singapore            222
Japan                205
Sweden               198
Belgium               54
Denmark               36
Name: Country, dtype: int64

In [52]:
# Which country has the most VIP+Preferred Customers combined?
orders[(orders['Label'] == 'VIP') | (orders['Label'] == 'Preferred')]['Country'].value_counts()

United Kingdom     221635
Germany              7349
EIRE                 7238
France               6301
Netherlands          2080
Spain                1569
Belgium              1557
Switzerland          1370
Portugal             1093
Australia            1028
Norway               1028
Channel Islands       589
Italy                 507
Finland               504
Cyprus                451
Sweden                273
Japan                 272
Singapore             222
Denmark               217
Israel                214
Iceland               182
Austria               158
Poland                149
Canada                135
Malta                  67
Lebanon                45
Greece                 32
Name: Country, dtype: int64